### PR TITLE
Turbulence model

### PR DESCRIPTION
**Pull request by elyqg**
This update add the turbulence model based on Suganami paper (Suganami, T., & Szeri, A. Z. (1979). A thermohydrodynamic analysis of journal bearings).

### CODE REVIEW

**Comment by raphaeltimbo** [comment]
Hi @elyqg.
Tests were not running for previous commits. Don't know exactly what was the error here on github.
After running the tests, we have some errors:

```
======================================== short test summary info =========================================
FAILED ross/fluid_flow/cylindrical.py::ross.fluid_flow.cylindrical.THDCylindrical
ERROR ross/tests/test_cylindrical.py::test_cylindrical_parameters - AttributeError: 'THDCylindrical' ob...
ERROR ross/tests/test_cylindrical.py::test_cylindrical_equilibrium_pos - AttributeError: 'THDCylindrica...
ERROR ross/tests/test_cylindrical.py::test_cylindrical_coefficients - AttributeError: 'THDCylindrical' ...
============== 1 failed, 440 passed, 2 skipped, 414 warnings, 3 errors in 111.09s (0:01:51) ==============

```

**Comment by elyqg** [comment]
Hi @raphaeltimbo. I will check the tests files.

**Review by raphaeltimbo — CHANGES_REQUESTED** [review]
Hi @elyqg and @marcusfilipesr 
Thank you for fixing the tests.
My only comment is regarding the main.py file in the project folder.
Could you please remove it before we merge the PR?
Thanks

**Comment by marcusfilipesr** [comment]
> Hi @elyqg and @marcusfilipesr Thank you for fixing the tests. My only comment is regarding the main.py file in the project folder. Could you please remove it before we merge the PR? Thanks

Good morning @raphaeltimbo,
We'll do this right away.

**Review by raphaeltimbo — APPROVED** [review]

**Pull request merged**
