### PR TITLE
Add save() and load() methods to manage ross results

### PR DESCRIPTION
**Pull request by rodrigomoliveira1**
Adds an abstract class `ST_Results` that holds a generic `save()` and `load()` methods.
The other classes will inherit these methods from `ST_Results`. It avoids redundancies by repetition of functions with the same functionality.
The user will be able to save the results of a given analysis and load it later, avoiding the need to re-run the entire analysis, which could be costly.

Example of how to use it:

```python
        >>> # Example running a stochastic unbalance response
        >>> from tempfile import tempdir
        >>> from pathlib import Path
        >>> import ross.stochastic as srs

        >>> # Running an example
        >>> rotors = srs.st_rotor_example()
        >>> freq_range = np.linspace(0, 500, 31)
        >>> n = 3
        >>> m = np.random.uniform(0.001, 0.002, 10)
        >>> p = 0.0
        >>> results = rotors.run_unbalance_response(n, m, p, freq_range)

        >>> # create path for a temporary file
        >>> file = Path(tempdir) / 'results.toml'
        >>> results.save(file)

        >>> # Loading file
        >>> results2 = srs.ST_ForcedResponseResults.load(file)
        >>> results2.magnitude.all() == results.magnitude.all()
        True
```

It is first applied to Stochastic ROSS. But the idea will be extended to ROSS.

### CODE REVIEW

**Comment by rodrigomoliveira1** [comment]
I'm facing a problem regarding to `TOML` while saving / loading `complex128` values. Despite I'm using the `TOML` enconder like: `toml.dump(data, f, encoder=toml.TomlNumpyEncoder())` to guarantee the numpy data is stored correctly and it returns an array when it is loaded, the complex values still returns as strings:

```python
>>> # loading results from an unbalance response
>>> results = ForcedRespnseResults.load(some_file)
>>> results.forced_response
['0j', '(4.546164340501405e-06+8.618002209913051e-18j)',
        '(1.9993323820899606e-05+2.808265984338688e-17j)',
        '(5.397777741253809e-05+6.855555853279516e-17j)',
        '(0.00013363345889400713+2.2244836428298553e-16j)',
        '(0.00042455441401372066+1.3017933041397235e-15j)',
        '(-0.0020262513775299524-2.704728865175545e-14j)',
        '(-0.00045190885817565814-2.463811835680412e-16j)',
        '(-0.0002971961665637599+5.070529833696888e-16j)',
        '(-0.0002387446702750649-2.605025098011477e-16j)' ...
```

@raphaeltimbo @GabrielBachmann if you guys have any idea of how to fix it.

**Comment by rodrigomoliveira1** [comment]
I found a way to go around this issue, but I don't know if it's the best way.
Also, `unbalance_response` demands a `Rotor` argument. So, when saving this analysis, an auxiliary file to save the rotor model is created:

```python
    @classmethod
    def load(cls, file):
        data = toml.load(file)
        # extract single dictionary in the data
        data = list(data.values())[0]
        for key, value in data.items():
            if isinstance(value, Iterable):
                data[key] = np.array(value)
                if data[key].dtype == np.dtype("<U49"):
                    data[key] = np.array(value).astype(np.complex128)

            if key == "rotor":
                aux_file = str(file)[:-5] + "_rotor" + str(file)[-5:]
                from ross.rotor_assembly import Rotor
                data[key] = Rotor.load(aux_file)

        return cls.read_toml_data(data)
```

```python
    def save(self, file):
        # get __init__ arguments
        signature = inspect.signature(self.__init__)
        args_list = list(signature.parameters)
        args = {arg: getattr(self, arg) for arg in args_list}
        try:
            data = toml.load(file)
        except FileNotFoundError:
            data = {}

        data[f"{self.__class__.__name__}"] = args
        with open(file, "w") as f:
            toml.dump(data, f, encoder=toml.TomlNumpyEncoder())

        if args["rotor"]:
            aux_file = str(file)[:-5] + "_rotor" + str(file)[-5:]
            args["rotor"].save(aux_file)
```

**Review by raphaeltimbo — APPROVED** [review]
I think everything is ok here. Could not understand why the travis build for the 3.6 version is failing. After solving that I think we can merge this.

**Comment by rodrigomoliveira1** [comment]
>I think everything is ok here. Could not understand why the travis build for the 3.6 version is failing. After solving that I think we can merge this.

Neither do I.
It raises the error below. It seems numpy could not receive a set of strings and convert it to complex. I'm looking for a solution to this problem.
```python
UNEXPECTED EXCEPTION: TypeError('must be real number, not numpy.str_',)

Traceback (most recent call last):

  File "/opt/python/3.6.7/lib/python3.6/doctest.py", line 1330, in __run

    compileflags, 1), test.globs)

  File "<doctest ross.stochastic.st_results.ST_Results.load[11]>", line 1, in <module>

  File "/home/travis/build/ross-rotordynamics/ross/ross/stochastic/st_results.py", line 147, in load

    data[key] = np.array(value).astype(np.complex128)

TypeError: must be real number, not numpy.str_
```

**Comment by rodrigomoliveira1** [comment]
I'm closing this PR to try solving the conflicts and the Travis issues. I couldn't reproduce the same error in my local machine.

**Comment by raphaeltimbo** [comment]
@rodrigomoliveira1 
Maybe this is related to the numpy version in each build.
I've checked and we have the following:

TRAVIS 3.6 - numpy 1.19.0
TRAVIS 3.7 - numpy 1.16.4
TRAVIS 3.8 - numpy 1.17.2

Appveyor 3.6 - numpy 1.19.4
Appveyor 3.7 - numpy 1.19.4
Appveyor 3.8 - numpy 1.19.4
Appveyor 3.6-x64 - numpy 1.19.4
Appveyor 3.7-x64 - numpy 1.19.4
Appveyor 3.8-x64 - numpy 1.19.4

I don't know why we have these differences between versions in the travis build, but maybe the problem is some bug related to the 1.19.0 version of numpy.

**Comment by raphaeltimbo** [comment]
@rodrigomoliveira1 , I have merged #709, which adds conda to our travis CI builds.
Now we have the numpy 1.19.2 version for all travis builds. 
You can reopen this PR or make a new one so we can test if the problem we were having here is still occurring.

**Pull request closed without merging**
