### PR TITLE
Add doctests

### LINKED ISSUE #84: Tests for the docstrings
The examples for the docstring also need to be tested. The example for `rs.Rotor` class was not working due to modifications such as the addition of the `.from_geometry()` and `.run()` methods. 
We need to implement automated tests (preferably integrated with our CI).
pytest is capable of running this kind of tests ([see here](https://docs.pytest.org/en/latest/doctest.html)).

- [x] Automate doctests
- [ ] Add to doctests appveyor
- [ ] Add doctests to travis CI

### PR DESCRIPTION
**Pull request by raphaeltimbo**
This PR adds the pytest.ini file which contains the `--doctest-modules` commands. Now, when pytest is called, it will run the tests in the /tests folder and also the examples in the docstrings. This helps us to keep our documentation up to date with the code.

Closes #84

### CODE REVIEW

**Comment by raphaeltimbo** [comment]
> There are some conflicts with the benchmark tests. I'm still trying to understand all the errors presented by the CI's. In a first look, I only this got:
> 
> * in [Campbell's Benchmark](https://github.com/ross-rotordynamics/ross/blob/master/Benchmarks/cProfile/Benchmark_Campbell_diagram.py) the `speed_range` is missing in `cProfile.run(rotor.run_campbell())`
> 
> EDIT 1:
> 
> * We are having a memory error while running `Benchmark_Freq_response.py`. I just tested it here and the RAM usage is huge. Maybe if we reduce the number of elements in the benchmark.

I am trying to solve the test problem by changing some commands at the appveyor / travis configuration files. With this, I hope that pytest will only run on the test folder and on the docstrings for files within the `~/ross/ross`. The benchmarks should not be executed by travis/appveyor.

**Comment by rodrigomoliveira1** [comment]
Even though we still have some errors, they are minors now. only assertion erros from rotor_assembly methods: 
- H_kappa
- kappa_mode
- kappa

**Comment by raphaeltimbo** [comment]
@rodrigomoliveira1 
Ok, after some changes in the doctests travis and appveyor are now passing.
I raised some issues regarding some problems that I have found while doing the tests (issues #145 and #146 )

**Comment by rodrigomoliveira1** [comment]
There is still a conflict, maybe, with the last PR (#147), so I'm not able to rebase and merge.

**Comment by rodrigomoliveira1** [comment]
I just saw you merged this PR branch (raphaeltimbo:add-doctests) in PR #147 
So, I believe it's better merge only the new PR to avoid this conflict, right?

**Comment by raphaeltimbo** [comment]
> I just saw you merged this PR branch (raphaeltimbo:add-doctests) in PR #147
> So, I believe it's better merge only the new PR to avoid this conflict, right?

I will merge this one and close submit a new PR to the add-doctests.

**Pull request merged**
