### PR TITLE
WIP - Correction of  6 dof Gyroscopic matrix

### PR DESCRIPTION
**Pull request by marcelosamora**
Co-authored-by: Vergilio T. S. Del Claro <vergiliotorezan@gmail.com>

### CODE REVIEW

**Comment by marcelosamora** [comment]
Hello (@raphaeltimbo )! My name is Marcelo(@marcelosamora ) I'm the new member of the project. I'm going to do some changes in the 6dof Gyroscopic matrix.

**Comment by marcelosamora** [comment]
Hello (@raphaeltimbo )! I have done a update in the Gyroscopic matrix in 6dof model. Any questions you have just let me know.

**Comment by raphaeltimbo** [comment]
Hi @marcelosamora !
Some tests for this PR are not passing.
[We use pytest to test our code.](https://ross.readthedocs.io/en/latest/contributing.html#step-5-testing-the-code)
If you need any help to set up pytest in your machine, let me know!

**Comment by raphaeltimbo** [comment]
Code here was merged on #834.

**Pull request closed without merging**
