### PR TITLE
Correction of 6 dof Gyroscopic matrix and TEST

### PR DESCRIPTION
**Pull request by marcelosamora**
Hello (@raphaeltimbo )! I have made changes to the gyroscopic matrix and Vergilio helped me checking the tests. I updated the gyroscopic matrix  in the tests and it seems they passed. I hope everthing know works!

### CODE REVIEW

**Comment by marcelosamora** [comment]
Hello Raphael! Does it still have errors right? As you can see in the picture attached I runned the tests in shaft elements, rotor assembly and test results and the 3 passed. I'm going to review again.
TESTE ROSS

**Comment by raphaeltimbo** [comment]
Hi @marcelosamora, sorry for the long time to respond.
Taking as an example the [Tests / build (3.6, ubuntu-latest) (pull_request) ](https://github.com/ross-rotordynamics/ross/pull/834/checks?check_run_id=3284980775), we can see that the tests that are not passing are related to the rubbing calculation (marked as F):

```
ross/tests/test_results.py .........                                     [ 77%]
ross/tests/test_rotor_assembly.py ..............s............s..s...     [ 85%]
ross/tests/test_rubbing.py ..FF                                          [ 86%]
ross/tests/test_shaft_element.py .......................                 [ 92%]
```

Since we know the code in the PR is right, values in the expected array that we have in the test are wrong.
To fix that, you could run the test in debug mode and get the value for `rub.forces_rub[rub.posRUB * 6, :]`, and then replace the expected values that we have in the test with these values.
Let me know if you need any help.

**Comment by marcelosamora** [comment]
Hi @raphaeltimbo! No worries! I created a rotor as it is in the test rubbing and Iprinted the rub.forces_rub[rub.posRUB * 6, :]
as you said to me. I updated the forces data but I think there is something wrong with the codes. I tried to check what I did but all the test are not passing as you can see in the picture attached. I  think maybe is something wrong in the ross.

**Comment by raphaeltimbo** [comment]
Hi @marcelosamora !

I am not aware how the test plugin in vscode works, but I think this could be related to some path issue.
Another way that you could try to run the tests is to go to the 'Terminal' within vscode and run the command `pytest`.
To run the command you should be in the tests parent directory (the ross directory with the `__init__.py` file in it).

**Comment by marcelosamora** [comment]
Hi @raphaeltimbo! Pytest

**Comment by marcelosamora** [comment]
Hi @raphaeltimbo! I think that now worked! As you can see in the pic the pytest for the test_rubbing is without errors.
Pytest

**Comment by raphaeltimbo** [comment]
Hi @marcelosamora ! All tests are passing. The marks showing failures are related to lint:
image

We use [black](https://ross.readthedocs.io/en/latest/contributing.html#code-style-black) to format our code.
But don't worry about that for now, I will make a commit to format the code using black and will merge the PR.

Thank you so much for fixing this!

**Comment by marcelosamora** [comment]
Great @raphaeltimbo ! Vergilio helped me with the black, but I'm still getting used to it. Sorry again! Thank you for your help!

**Pull request merged**
