### PR TITLE
 Test for the 'MagneticBearingElement' class

### PR DESCRIPTION
**Pull request by davidjgm**
Add a test for the 'MagneticBearingElement' class inside 'test_bearing_seal_element.py'

### CODE REVIEW

**Comment by rodrigomoliveira1** [comment]
@davidjgm, I couldn't merge this PR due some conflicts. 
Some commits are repeated (from the last PR you commited to create the MagneticBearing class). You can try reversing the commits or opening a new PR without them.

**Comment by raphaeltimbo** [comment]
> @davidjgm, I couldn't merge this PR due some conflicts.
> Some commits are repeated (from the last PR you commited to create the MagneticBearing class). You can try reversing the commits or opening a new PR without them.

It looks like the conflicts have been solved, right?

**Comment by rodrigomoliveira1** [comment]
> It looks like the conflicts have been solved, right?

Not yet. The conflict message is still here.

**Comment by raphaeltimbo** [comment]
> > It looks like the conflicts have been solved, right?
> 
> Not yet. The conflict message is still here.

To me it is looking like this:
image

**Comment by rodrigomoliveira1** [comment]
Here, it's looking like this:

image

**Comment by rodrigomoliveira1** [comment]
I think you can merge it anyway.

**Comment by raphaeltimbo** [comment]
> I think you can merge it anyway.

Ok I will try. Let's hope everything goes ok :sweat_smile:

**Comment by davidjgm** [comment]
I had some problems with my fork of the repository. If the merge fails I can try to fix the repeated commits.

**Pull request merged**
