### PR TITLE
Add bearing instantiation from fluid flow

### PR DESCRIPTION
**Pull request by flaviorangel**
A bearing can now be instantiated from fluid flow by giving fluid flow parameters to a bearing method.

### CODE REVIEW

**Comment by JuliaMota** [comment]
@raphaeltimbo Why have these tests failed? Do you know?

**Comment by flaviorangel** [comment]
> @raphaeltimbo Why have these tests failed? Do you know?

Same thing happening on the other pull request we did. Can this be related to the tests we added?

**Comment by rodrigomoliveira1** [comment]
Apparently it's an assertion error in `def test_stiffness_matrix()` test (example 5.5.1).
You can check the travis' log in this [link](https://travis-ci.com/ross-rotordynamics/ross/jobs/202482946)
Have this test succeeded in your own build? 

Capturar

**Comment by flaviorangel** [comment]
> Apparently it's an assertion error in `def test_stiffness_matrix()` test (example 5.5.1).
> You can check the travis' log in this [link](https://travis-ci.com/ross-rotordynamics/ross/jobs/202482946)
> Have this test succeeded in your own build?
> 
> Capturar

You are right. I thought I had solved this error. I'll work on it. Thank you.

**Pull request merged**
